import MyProfilePic from './components/MyProfilePic';
import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
    title: "Adnan's Blog",
    description: 'Generated by Mirza Adnan',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="dark:bg-black/90">
                <Navbar />
                <MyProfilePic />
                {children}
            </body>
        </html>
    );
}
